#!/bin/bash

# Aquire RHCOS ova needed for install

OCP_RELEASE=$1
OCP_VERSION=$(echo ${OCP_RELEASE} | awk -F "." '{ print $1"."$2 }')
OVA_NUM=0
RELEASE_NUM=$(echo ${OCP_RELEASE} | awk -F "." '{ print $3 }')

#echo "release is ${OCP_RELEASE}"
#echo "release num is ${RELEASE_NUM}"
#echo "OCP version is ${OCP_VERSION}"


for release in  $(curl -sL mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/${OCP_VERSION} | grep ${OCP_VERSION} | sed -n 's/.*\([0-9]\.[0-9]*\.[0-9]*\).*/\1/p' | awk -F "." '{ print $3 }' | sort -rh);
do
	if (( release <= RELEASE_NUM )); then
		OVA_VERSION=$release;
		break
	else
		continue
	fi	
done

printf "${OCP_VERSION}.${OVA_VERSION}"
